title = "SSVD Ops Repo Gitleaks Config"

[extend]
useDefault = true

[[rules]]
id = "aws-account-id"
description = "AWS account IDs are not secrets by themselves"
regex = '''\b[0-9]{12}\b'''
tags = ["aws"]
allowlist = { regexes = ['''123456789012''', '''824090260951'''] }
