replicaCount: 3

image:
  repository: 824090260951.dkr.ecr.ap-south-2.amazonaws.com/ssvd-bhoomi-report
  tag: "main"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:ap-south-2:824090260951:regional/webacl/ssvd-prod/default
  hosts:
    - host: bhoomi.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
