apiVersion: v2
name: myapp
description: Helm chart for the SSVD Bhoomi Report application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Srisatvam SRE
keywords:
  - ssvd
  - bhoomi
  - gitops
