replicaCount: 1

image:
  repository: 824090260951.dkr.ecr.ap-south-2.amazonaws.com/ssvd-bhoomi-report
  tag: "sha-84b3fc4804d85b2c28a4d6868f77181a3947c8e0"

autoscaling:
  enabled: false

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
  hosts:
    - host: bhoomi-dev.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
